# Generated by Django 4.1.1 on 2022-09-15 13:07

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='asking_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money(1000, 'USD')), djmoney.models.validators.MaxMoneyValidator(djmoney.money.Money(100000, 'USD'))]),
        ),
    ]
