# Generated by Django 4.1.1 on 2022-09-26 04:07

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0003_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycar',
            name='commission',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='buycar',
            name='net_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
