# Generated by Django 4.1.1 on 2022-09-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0006_buycar_commission_buycar_commission_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='buycar',
            name='commission_currency',
        ),
        migrations.RemoveField(
            model_name='buycar',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='buycar',
            name='net_amount_currency',
        ),
    ]
