# Generated by Django 4.1.1 on 2022-09-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0007_remove_buycar_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
