# Generated by Django 4.1.1 on 2022-09-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0008_alter_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('Car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_application.car')),
            ],
        ),
    ]
