# Generated by Django 4.1.1 on 2022-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0009_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(null=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(upload_to='./'),
        ),
    ]
