# Generated by Django 4.1.1 on 2022-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0010_alter_car_image_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(null=True, upload_to='car/%d'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(upload_to='car/%d'),
        ),
    ]
