# Generated by Django 4.1.1 on 2022-10-05 10:04

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_application', '0014_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
